# **Artificial Neural Network Regression**

> Build an ANN Regression model to predict the electrical energy output of a Combined Cycle Power Plant.





### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
print(tf.__version__)

2.18.0


## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
df = pd.read_excel('Folds5x2_pp.xlsx')
df.head(5)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [6]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 40)

## Part 2 - Building the ANN

### Initializing the ANN

In [29]:
ANN = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [30]:
ANN.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the second hidden layer

In [31]:
ANN.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the output layer

In [32]:
ANN.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [40]:
ANN.compile(loss = "mean_squared_error",
            optimizer = "adam",
            metrics = ['mae','mse'])

### Training the ANN model on the Training set

In [41]:
history = ANN.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.6128 - mae: 3.9768 - mse: 25.6128
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.8034 - mae: 3.9852 - mse: 25.8034
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26.1791 - mae: 4.0255 - mse: 26.1791
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.6143 - mae: 3.8631 - mse: 23.6143
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 24.7772 - mae: 3.8745 - mse: 24.7772
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 25.7853 - mae: 3.9647 - mse: 25.7853
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.1274 - mae: 3.7809 - mse: 23.1274
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23.5270 - mae: 3.8223 - mse: 23.5270
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 24.9725 - mae: 3.8182 - mse: 24.9725
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 24.2988 - mae: 3.8888 - mse: 24.2988
Epoch 11/100
240/24

### Predicting the results of the Test set

In [38]:
y_pred = ANN.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[438.8  430.29]
 [484.57 484.45]
 [467.17 472.16]
 ...
 [451.24 443.48]
 [458.7  458.62]
 [450.72 443.31]]
